# version: '3.7'

services:
  web:
    build: .
    ports:
      - "9044:80"
    extra_hosts:
      - "192.168.2.226:192.168.2.226"
      - "192.168.2.32:192.168.2.32"
      - "192.168.2.97:192.168.2.97"
    volumes:
      - .:/var/www/html/hris
