name: Development Force Update
on:
  push:
    branches:
      - master

env:
  SWR_REGISTRY: swr.ap-southeast-3.myhuaweicloud.com   # Huawei Cloud SWR registry URL, e.g., swr.ap-southeast-1.myhuaweicloud.com
  SWR_NAMESPACE: ap-southeast-3 # SWR namespace or project ID
  SWR_IMAGE_NAME: facial-worker-sttherese # Name of the Docker image in SWR
  SWR_LOGIN_KEY: ${{ secrets.SWR_LOGIN_KEY }}
  SWR_AK_KEY: ${{ secrets.SWR_AK_KEY }}
  SWR_ORGANIZATION: container-pti

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: master
        
      # Add a step to delete the .env file
    - name: Delete .env file
      run: |
        rm -f env
      
    # Add a step to rename .env_demo to .env
    - name: Rename env_prod to .env
      run: |
        mv env_prod env
      
    - name: Docker Build
      run: |
        docker build -t ${{ env.SWR_IMAGE_NAME }}:latest-${{github.event.head_commit.id}} .
      
    - name: Login to SWR HUAWEI
      run: |
        docker login -u ${{ env.SWR_NAMESPACE }}@${{ env.SWR_AK_KEY }} -p ${{ env.SWR_LOGIN_KEY }} ${{ env.SWR_REGISTRY }}
      
    - name: Add SWR TAG
      run: |
        docker tag ${{ env.SWR_IMAGE_NAME }}:latest-${{github.event.head_commit.id}} ${{ env.SWR_REGISTRY }}/${{ env.SWR_ORGANIZATION }}/${{ env.SWR_IMAGE_NAME }}:latest-${{github.event.head_commit.id}}

    - name: PUSH SWR 
      run: |
        docker push ${{ env.SWR_REGISTRY }}/${{ env.SWR_ORGANIZATION }}/${{ env.SWR_IMAGE_NAME }}:latest-${{github.event.head_commit.id}}
